---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop-ingress
  namespace: pets
spec:
  rules:
  - http:
      paths:
      - path: /products2
        pathType: Prefix
        backend:
          service:
            name: product-service
            port:
              number: 3002
      - path: /
        pathType: Prefix
        backend:
          service:
            name: store-front
            port:
              number: 80